# Installed Gems
plugins:
  - jekyll-seo-tag

# Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-US # Set the site language
title: "Popfolio" # Site name or title, also used in jekyll-seo-tag
css_inline: false # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
